### ISSUE TITLE
Functions to set reaction rates

### ISSUE THREAD

**Issue by EricJIsaac** [readdy/readdy#134]
Hello,

I am currently using ReaDDy to construct a real-time simulation with editable run-time parameters.

I am requesting functions in the C++ API to edit the rates of Structural and Spatial Topology reactions after their construction. Currently I am only using the Topology Reactions, but I would ultimately like to be able to edit the rate of any reaction.

e.g.
reaction = topologies.spatialReactionByName("...")
reaction.setRate( new Rate );

Preferably, this function would also update the reaction rates for the appropriate existing typologies, but that is more a matter of convenience for me personally, since functions to do so already exist.

Thanks,
-Eric

**Comment by clonker** [comment]
Hi Eric,
I have now added modifying access rates of reactions, the changes should carry over immediately (as in: in the next time step) to the existing topologies (PR #137). A special case are structural topology reactions as the rate is determined by the rate function. Small example of adapting rates for all kinds of reactions:

```cpp
Simulation sim ("SingleCPU");
sim.context().topologyRegistry().addType("Polymer");
sim.context().particleTypes().addTopologyType("A", 1);
sim.context().particleTypes().add("B", 1.);
sim.context().topologyRegistry().addSpatialReaction("Attach: Polymer(A) + (B) -> Polymer(A--A)", 1., 5.);
sim.context().reactions().add("myfus: B +(5) B -> B", 10);
sim.context().reactions().add("myconv: B -> B", 10);

sim.addParticle("B", 0., 0., 0.);
sim.addTopology("Polymer", {sim.createTopologyParticle("A", {0., 0., 0.})});
sim.context().topologyRegistry().configureBondPotential("A", "A", {10., 10.});

auto loop = sim.createLoop(1.5);

loop.addCallback([&](const auto t) {
    // triggers evaluation of rate functions for each topology
    for (auto topology : sim.stateModel().getTopologies()) {
        topology->updateReactionRates(
                sim.context().topologyRegistry().structuralReactionsOf(topology->type())
        );
    }
    // change spatial topology reaction rate
    sim.context().topologyRegistry().spatialReactionByName("Attach").rate() = 5000;
    // change unimolecular reaction rate
    sim.context().reactions().order1ByName("myconv")->rate() = 100;
    // change bimolecular reaction rate
    sim.context().reactions().order2ByName("myfus")->rate() = 100;
});

loop.run(500);
```
Also there is now a `addCallback` method to the simulation loop so that you can do your rate modification in there if desired. It is executed in the very beginning and after each time step similar to observables.

**Comment by EricJIsaac** [comment]
Thank you!
