### ISSUE TITLE
Growing Polymer with Constant Concentration

### ISSUE THREAD

**Issue by JoulesJ** [readdy/readdy#156]
Hello,

I would like to modify the Growing Polymer example (https://readdy.github.io/demonstration/growing_polymer) in such a way, that I can keep the concentration of the diffusing particles constant. 
For the dissociation I would fix the problem by changing the dissociated particle type to a non-interacting particle. However, for the spacial reaction that adds a particle to the topology, I couldn't come up with a way to add an additional particle (at a random position).
Is there an "easy" fix to this problem that I am missing?

Kind regards,
Julia

**Comment by chrisfroe** [comment]
Hi Julia,

you can register another particle species `F`, that diffuses freely in the box and absorbs and creates `Substrate` particles, via the two reactions `F <--> F + Substrate`.
```python
system.reactions.add_fusion(
    "factory-fusion", "F", "Substrate", "F", factory_on_rate,
    factory_reaction_radius, weight1=0., weight2=1.)
system.reactions.add_fission(
    "factory-fission", "F", "F", "Substrate", factory_off_rate,
    factory_reaction_radius, weight1=0., weight2=1.)
```
by setting the weights as above you ensure, that the factory particles stay at their position while absorbing/creating a `Substrate` particle.

The constant concentration that you would get from that is a result of:
- the number of factory particles
- the on- and off rates
- the reaction radius
- the amount of particles absorbed from your growing polymer per time
i.e. it is not straightforward to set the value of the concentration a priori. There are equations to approximate this under certain conditions. Let me know if you would be interested.

Additionally you can confine the factory particles to a certain region of the simulation box (e.g. the boundaries) using external potentials, if you want to avoid particles appearing very close to the polymer at random.

Hope that helps,
Chris

**Comment by JoulesJ** [comment]
Hi Chris,
Thanks very much for your detailed answer. Having this additional particle looks promising. Could you point me in the right direction for the theory on how to set the rates? It does not seem very straightforward to me since it will also depend on the diffusion of F and Substrate, hence how often they encounter each other at a given concentration. 
Regards,
Julia

**Comment by chrisfroe** [comment]
Hi Julia,

I setup an example notebook (https://readdy.github.io/demonstration/constant_concentration), that describes the theory and runs a simulation, whose concentration of S particles converges to the pre-defined value after a given time.

In principle you can adjust all values (forward and backward propensity, diffusion constants, reaction radius) to fit your desired concentration as long as the factory reactions happen in the well-mixed regime (kappa R < 1).

Note that the equilibrium value of concentration of S does __not__ depend on the number of factory particles (in contrast to what I said earlier) under the well-mixed assumption. However larger number of factory particles decreases the time to reach equilibrium, at the cost of computational performance, since readdy's computation time scales linearly in the number of particles.

Best,
Chris

**Comment by JoulesJ** [comment]
Hi Chris,
That is very helpful and seems to be adjustable to fix my problem.
Thanks very much,
Julia
