### ISSUE TITLE
Unable to open file from killed simulation run

### ISSUE THREAD

**Issue by jansteinkuehler** [readdy/readdy#220]
Hi,
I'm trying to recover data from a run that was killed (due to timeout). When I try to open the file I get:

t = readdy.Trajectory(file)
OSError: Unable to open file (file is already open for write (may use <h5clear file> to clear file consistency flags))

I tried:
$ h5clear -s file

But now I get:
t = readdy.Trajectory(file)
RuntimeError: Unable to get link info (bad object header version number)

Is this expected and/or is there some other way I could recover the trajectory?

Thanks
Jan

**Comment by clonker** [comment]
Hi Jan,
this seems rough. You could try to debug your file with [h5check](https://support.hdfgroup.org/products/hdf5_tools/h5check.html) and/or [h5debug](https://manpages.debian.org/testing/hdf5-tools/h5debug.1.en.html) to get some more information on what is wrong with it. Generally it seems to me that `h5clear` clears too much and there is nothing left. Another tool for these cases is [h5recover](https://gitlabext.iag.uni-stuttgart.de/libs/hdf5/-/tree/bffa7bd55d942681bdd11be775090d3c72a15bd5/tools/h5recover). Generally it is to be expected that a file corrupts when there is a write process which gets killed. One way to mitigate this is to open a new trajectory file every once in a while so that at least the largest portion of the file are not affected. This is not implemented right now, though (and I would be happy to help if someone volunteered to implement that :slightly_smiling_face:)
A similar mechanism is [checkpointing](https://readdy.github.io/simulation.html#checkpointing) to save the system's state every `n` steps.
Best!

**Comment by jansteinkuehler** [comment]
Hi clonker,
thanks for the quick reply. I presumably won't be the person to implement a multi-trajectory solution but I'm interested to see if I can find a way to fix such h5 files. 

I understand that the file might be corrupted when killed while writing but (without knowing the details of the h5 format) I would assume that a large portion of the data is unaffected.

I wonder if it would be possible to fix a h5 file, in particular if one has a checkpoint file (i.e. rewind to the last good state). In my case this would help me to submit jobs that run as long the cluster allows without timing the number of steps for each run. I will look it into this and will be happy for any further advice you can give.

Best,
Jan

**Comment by clonker** [comment]
Dear Jan, 
aside from the tools I linked I am not sure what else can be done. Indeed I assume that large portions of the file are intact, but I am not aware of a straightforward way of recovering these.
For future runs you can subdivide your simulations though: record checkpoints and re-run your simulation script with the state loaded from the last checkpoint, writing into a new trajectory file. If you do this too frequently, you will run into performance issues, but I guess it is feasible to do this every couple hundred or thousand steps, depending on the complexity of your system.
Cheers!

**Comment by clonker** [comment]
Hi Jan,

thank you very much for sharing your insight! I'll put a remark in the documentation.

Cheers,
Moritz
